### ISSUE TITLE
forward not working

### ISSUE THREAD

**Issue by k1rOuX** [Traptricker/AFK_Apex_Bot#3]
Hi, nice job! All work fine for me, in both modes (k/d mode or XP mode) except that it never move, it only jump (and use abilities on k/d mode). 
I checked to have the correct keybinds. Also tryed to reset the Apex config file to default. Is it a normal behavior or is it supposed to move in-game ?

**Comment by Traptricker** [comment]
That is normal behavior

**Comment by JacksonElia** [comment]
Hey,

That’s normal behavior, it doesn’t move cause I’m not that good at programming.
